export const ListBaverages = [
  {
    title: "Original",
    desc: "",
    img: "",
    categories: ["Beverages", "BrewedCoffee"],
    price: "",
  },
  {
    title: "ColdBrewed",
    desc: "",
    img: "",
    categories: ["Beverages", "BrewedCoffee"],
    price: "",
  },
  {
    title: "Misto",
    desc: "",
    img: "",
    categories: ["Beverages", "BrewedCoffee"],
    price: "",
  },
  {
    title: "Vanilla Sweat Cream Cold Brew",
    desc: "",
    img: "",
    categories: ["Beverages", "BrewedCoffee"],
    price: "",
  },
  {
    title: "Citrus Mint Hot Tea",
    desc: "",
    img: "",
    categories: ["Beverages", "BrewedTea"],
    price: "",
  },
  {
    title: "Iced Shaken Lemonade Tea",
    desc: "",
    img: "",
    categories: ["Beverages", "BrewedTea"],
    price: "",
  },
  {
    title: "TVNA Chai Hot Tea",
    desc: "",
    img: "",
    categories: ["Beverages", "BrewedTea"],
    price: "",
  },
  {
    title: "TVNA Chamomile Hot Tea",
    desc: "",
    img: "",
    categories: ["Beverages", "BrewedTea"],
    price: "",
  },
  {
    title: "TVNA Earl Grey Hot Tea",
    desc: "",
    img: "",
    categories: ["Beverages", "BrewedTea"],
    price: "",
  },
  {
    title: "Caramel Macchiato",
    desc: "",
    img: "",
    categories: ["Beverages", "Esspresso Based"],
    price: "",
  },
  {
    title: "Espresso",
    desc: "",
    img: "",
    categories: ["Beverages", "Esspresso Based"],
    price: "",
  },
  {
    title: "Iced Espresso & Matcha Fusion",
    desc: "",
    img: "",
    categories: ["Beverages", "Esspresso Based"],
    price: "",
  },
  {
    title: "Black Team Latte",
    desc: "",
    img: "",
    categories: ["Beverages", "Latte Tea"],
    price: "",
  },
  {
    title: "Chai Tea Latte",
    desc: "",
    img: "",
    categories: ["Beverages", "Latte Tea"],
    price: "",
  },
  {
    title: "Earl Grey Tea Latte",
    desc: "",
    img: "",
    categories: ["Beverages", "Latte Tea"],
    price: "",
  },
  {
    title: "Green Tea Latte",
    desc: "",
    img: "",
    categories: ["Beverages", "Latte Tea"],
    price: "",
  },
];
export const ListFood = [
  {
    title: "Almond Whirl Choco Chips Danish",
    desc: "",
    img: "",
    categories: ["Foods", "Bakery"],
    price: "",
  },
  {
    title: "Butter Croissant",
    desc: "",
    img: "",
    categories: ["Foods", "Bakery"],
    price: "",
  },
  {
    title: "Choco Chops Pistachio Pocket",
    desc: "",
    img: "",
    categories: ["Foods", "Bakery"],
    price: "",
  },
  {
    title: "Choco Chunk Praline Muffin",
    desc: "",
    img: "",
    categories: ["Foods", "Bakery"],
    price: "",
  },
  {
    title: "Chocolate Croisant",
    desc: "",
    img: "",
    categories: ["Foods", "Bakery"],
    price: "",
  },
  {
    title: "Cinnamon Rolls",
    desc: "",
    img: "",
    categories: ["Foods", "Bakery"],
    price: "",
  },
  {
    title: "Glutten Dree Almond Financier",
    desc: "",
    img: "",
    categories: ["Foods", "Bakery"],
    price: "",
  },
  {
    title: "Smoked Beef Emmental Croisant",
    desc: "",
    img: "",
    categories: ["Foods", "Bakery"],
    price: "",
  },
  {
    title: "Wild Berry Muffin",
    desc: "",
    img: "",
    categories: ["Foods", "Bakery"],
    price: "",
  },
  {
    title: "Apple and Connamon Crumble",
    desc: "",
    img: "",
    categories: ["Foods", "Cakes And Sweat"],
    price: "",
  },
  {
    title: "Chocolate Ganache and Rasberry Cake",
    desc: "",
    img: "",
    categories: ["Foods", "Cakes And Sweat"],
    price: "",
  },
  {
    title: "Espresso Brownies",
    desc: "",
    img: "",
    categories: ["Foods", "Cakes And Sweat"],
    price: "",
  },
  {
    title: "Green Tea and Ogura Swiss Roll",
    desc: "",
    img: "",
    categories: ["Foods", "Cakes And Sweat"],
    price: "",
  },
  {
    title: "Bahn Mie Chicken Baquette",
    desc: "",
    img: "",
    categories: ["Foods", "Sanswiches"],
    price: "",
  },
  {
    title: "Honey Mustard Rpast Beef Focaccia",
    desc: "",
    img: "",
    categories: ["Foods", "Sanswiches"],
    price: "",
  },
  {
    title: "Mediterranean Chicken Sandwich",
    desc: "",
    img: "",
    categories: ["Foods", "Sanswiches"],
    price: "",
  },
  {
    title: "Smoked Beef Mushroom and Cheese Panini",
    desc: "",
    img: "",
    categories: ["Foods", "Sanswiches"],
    price: "",
  },
  {
    title: "Spicy Roast Beef Dark Ciabatta",
    desc: "",
    img: "",
    categories: ["Foods", "Sanswiches"],
    price: "",
  },
  {
    title: "Tuna Black Pepper Sour Dough Bread",
    desc: "",
    img: "",
    categories: ["Foods", "Sanswiches"],
    price: "",
  },
  {
    title: "Cheese Quiche",
    desc: "",
    img: "",
    categories: ["Foods", "Savory Pies"],
    price: "",
  },
  {
    title: "Smoked Beef Quiche",
    desc: "",
    img: "",
    categories: ["Foods", "Savory Pies"],
    price: "",
  },
];
